In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
url = 'https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv'

df =  pd.read_csv(url)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
# thing to notice in the above data set is the bedrooms in missing for one of the values then the best way to prevent this is to we will be taking madian of the following bedrooms that are given and will be putting it into the missing values.

import math # importing the math module to use the mathematical fucntions.

med_bed = math.floor(df.bedrooms.median())
med_bed

4

In [8]:
df.bedrooms = df.bedrooms.fillna(med_bed)


In [9]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [13]:
reg.intercept_ # this is the intercept b that is the constant after every equations 

221323.00186540396

In [21]:
model_value=reg.predict([[3000,3,40]]) # this is the predicted value that is given according to the linear reg model.
model_value 

array([498408.25158031])

In [20]:
# manually calculating the results 
manual_value = 112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540396
manual_value

498408.251574024

In [23]:
model_value - manual_value

array([6.28270209e-06])